name: deno

on: [push]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno fmt --config deno.json --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno lint --config deno.json
  
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      
      - run: cargo install wasm-pack
      - run: deno task build

      - uses: denoland/deployctl@v1
        with:
          project: images-proxy
          entrypoint: src/main.ts